# Generated by Django 5.0.4 on 2024-07-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoEmpleado',
        ),
    ]
